=== powerd6-old/schemas/schemas/injury.json
{
  "title": "Injury",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.powerd6.org/schemas/injury.json",
  "type": "object",
  "required": ["id", "name", "description"],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "$ref": "https://schemas.powerd6.org/schemas/markdown-string.json"
    },
    "effects": {
      "type": "array",
      "items": {
        "allOf": [
          { "$ref": "https://schemas.powerd6.org/schemas/reference.json" }
        ],
        "properties": {
          "model": { "const": "effect" }
        }
      }
    }
  },
  "additionalProperties": false
}

=== powerd6-old/schemas/docs/examples/injury.json
{
  "id": "harsh",
  "name": "Harsh",
  "description": "Harsh injuries are life-changing events that may change how your character is forever. While they eventually heal and you adapt, you are not quite the same anymore.",
  "effects": [
    {
      "type": "effect",
      "id": "disadvantage-movement"
    }
  ]
}
