=== powerd6-old/schemas/schemas/spell.json
{
  "title": "Spell",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.powerd6.org/schemas/spell.json",
  "type": "object",
  "required": ["id", "name", "description", "effects", "learning_requirements"],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "$ref": "https://schemas.powerd6.org/schemas/markdown-string.json"
    },
    "learning_requirements": {
      "$ref": "https://schemas.powerd6.org/schemas/markdown-string.json"
    },
    "activation_requirements": {
      "$ref": "https://schemas.powerd6.org/schemas/markdown-string.json"
    },
    "effects": {
      "type": "array",
      "items": {
        "$ref": "https://schemas.powerd6.org/schemas/effect.json"
      }
    }
  },
  "additionalProperties": false
}

=== powerd6-old/schemas/docs/examples/spell.json
{
  "id": "strength-in-numbers",
  "name": "Strength In Numbers",
  "description": "Your blood rushes as you see yourself surrounded by foes and allies alike.\nWhether it is the impulse to protect your comrades, or simply the desire to see blood, this energizes you.",
  "learning_requirements": "You must have {.name}[$.content.attribute[?(@.id=='strength')]] score of at least 3.",
  "activation_requirements": "You must be bleeding or have a injury.",
  "effects": [
    {
      "type": "effect",
      "id": "increase-strenght-1d6"
    },
    {
      "type": "effect",
      "id": "heal-ally-count"
    }
  ]
}
